In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\ruano\anaconda3\lib\site-packages (9.0.0)

In [2]:
import mysql.connector

# Connection configuration
conexion = mysql.connector.connect(
  host="localhost",
  user="root",
  password="datapoet",
  database="dap1"
)

# Connection verification
if conexion.is_connected():
    print("Conexión exitosa a MySQL")

Conexión exitosa a MySQL

In [17]:
!pip install ipython-sql

Requirement already satisfied: ipython-sql in c:\users\ruano\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (3.11.0)
Requirement already satisfied: ipython in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (8.25.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (2.0.30)
Requirement already satisfied: sqlparse in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (0.5.1)
Requirement already satisfied: six in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ruano\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ruano\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: decorator in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\ruano\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\ruano\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [19]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [36]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\ruano\anaconda3\lib\site-packages (2.0.30)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ruano\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ruano\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ---------------------------------------- 0.0/45.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/45.0 kB ? eta -:--:--
   --------- ------------------------------ 10.2/45.0 kB ? eta -:--:--
   --------------------------- ------------ 30.7/45.0 kB 262.6 kB/s eta 0:00:01
   ---------------------------------------- 45.0/45.0 kB 373.5 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

#### 2.2.3.1 **World Bank Indicators**

For the World Bank data, I first refined the list of relevant countries by excluding categories like regions and areas from the Excel file. I then imported this refined data into the **wb_countries** table in **Navicat**, resulting in a table with 216 records, each representing a country with its relevant information. This table served as a reference for comparing with other indicator tables imported separately. Subsequently, the data from the four separate indicator tables were consolidated into a single table, **wb_values**. SQL queries were used to verify and compare record counts across tables to ensure data consistency, and joins were performed to integrate the tables into the final data model.

Here is an example of a join between **wb_countries**, with the refined list of countries, and **____wb_gdppc**, the imported table for one of the indicators:

In [49]:
from sqlalchemy import create_engine
import pandas as pd

# Configure connection chain
engine = create_engine('mysql+pymysql://root:datapoet@localhost/dap1')

# Connect and execute query
query = '''SELECT c.country_code, g.country_code AS country_code_gdp
FROM wb_countries AS c
LEFT JOIN ____wb_gdppc AS g 
     ON c.country_code = g.country_code
WHERE g.country_code IS NULL;'''

df = pd.read_sql(query, engine)

# Show results
df.head()

Empty DataFrame
Columns: [country_code, country_code_gdp]
Index: []

Here, we see an example of a join between **wb_countries**, which contains the predefined list of countries, and **____wb_gdppc**, one of the imported indicator tables. By comparing the **country_code** from both tables using a LEFT JOIN, it is evident that there are no discrepancies between them. The country code serves as the common key for both tables. Subsequently, after verification, all four tables were merged into the parent table **wb_values** using the following query:

INSERT INTO wb_values (
  country_id,
  indicator_id,
  `1960`, `1961`, `1962`, `1963`, `1964`, `1965`, `1966`, `1967`, `1968`, `1969`,
  `1970`, `1971`, `1972`, `1973`, `1974`, `1975`, `1976`, `1977`, `1978`, `1979`,
  `1980`, `1981`, `1982`, `1983`, `1984`, `1985`, `1986`, `1987`, `1988`, `1989`,
  `1990`, `1991`, `1992`, `1993`, `1994`, `1995`, `1996`, `1997`, `1998`, `1999`,
  `2000`, `2001`, `2002`, `2003`, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`,
  `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`,
  `2020`, `2021`, `2022`, `2023`  
) SELECT
    wb_countries.id,
    wb_indicators.id,
    ____wb_gdppc.`1960`,
    ____wb_gdppc.`1961`,
    ____wb_gdppc.`1962`,
    ____wb_gdppc.`1963`,
    ____wb_gdppc.`1964`,
    ____wb_gdppc.`1965`,
    ____wb_gdppc.`1966`,
    ____wb_gdppc.`1967`,
    ____wb_gdppc.`1968`,
    ____wb_gdppc.`1969`,
    ____wb_gdppc.`1970`,
    ____wb_gdppc.`1971`,
    ____wb_gdppc.`1972`,
    ____wb_gdppc.`1973`,
    ____wb_gdppc.`1974`,
    ____wb_gdppc.`1975`,
    ____wb_gdppc.`1976`,
    ____wb_gdppc.`1977`,
    ____wb_gdppc.`1978`,
    ____wb_gdppc.`1979`,
    ____wb_gdppc.`1980`,
    ____wb_gdppc.`1981`,
    ____wb_gdppc.`1982`,
    ____wb_gdppc.`1983`,
    ____wb_gdppc.`1984`,
    ____wb_gdppc.`1985`,
    ____wb_gdppc.`1986`,
    ____wb_gdppc.`1987`,
    ____wb_gdppc.`1988`,
    ____wb_gdppc.`1989`,
    ____wb_gdppc.`1990`,
    ____wb_gdppc.`1991`,
    ____wb_gdppc.`1992`,
    ____wb_gdppc.`1993`,
    ____wb_gdppc.`1994`,
    ____wb_gdppc.`1995`,
    ____wb_gdppc.`1996`,
    ____wb_gdppc.`1997`,
    ____wb_gdppc.`1998`,
    ____wb_gdppc.`1999`,
    ____wb_gdppc.`2000`,
    ____wb_gdppc.`2001`,
    ____wb_gdppc.`2002`,
    ____wb_gdppc.`2003`,
    ____wb_gdppc.`2004`,
    ____wb_gdppc.`2005`,
    ____wb_gdppc.`2006`,
    ____wb_gdppc.`2007`,
    ____wb_gdppc.`2008`,
    ____wb_gdppc.`2009`,
    ____wb_gdppc.`2010`,
    ____wb_gdppc.`2011`,
    ____wb_gdppc.`2012`,
    ____wb_gdppc.`2013`,
    ____wb_gdppc.`2014`,
    ____wb_gdppc.`2015`,
    ____wb_gdppc.`2016`,
    ____wb_gdppc.`2017`,
    ____wb_gdppc.`2018`,
    ____wb_gdppc.`2019`,
    ____wb_gdppc.`2020`,
    ____wb_gdppc.`2021`,
    ____wb_gdppc.`2022`,
    ____wb_gdppc.`2023` 
FROM
  ____wb_gdppc
  JOIN wb_countries ON ____wb_gdppc.country_code = wb_countries.country_code
  JOIN wb_indicators ON ____wb_gdppc.indicator_code = wb_indicators.indicator_code;
  
#INSERT INTO wb_values (
  country_id,
  indicator_id,
  `1960`, `1961`, `1962`, `1963`, `1964`, `1965`, `1966`, `1967`, `1968`, `1969`,
  `1970`, `1971`, `1972`, `1973`, `1974`, `1975`, `1976`, `1977`, `1978`, `1979`,
  `1980`, `1981`, `1982`, `1983`, `1984`, `1985`, `1986`, `1987`, `1988`, `1989`,
  `1990`, `1991`, `1992`, `1993`, `1994`, `1995`, `1996`, `1997`, `1998`, `1999`,
  `2000`, `2001`, `2002`, `2003`, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`,
  `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`,
  `2020`, `2021`, `2022`, `2023` 
) SELECT
    wb_countries.id,
    wb_indicators.id,
    ____wb_netmigration.`1960`,
    ____wb_netmigration.`1961`,
    ____wb_netmigration.`1962`,
    ____wb_netmigration.`1963`,
    ____wb_netmigration.`1964`,
    ____wb_netmigration.`1965`,
    ____wb_netmigration.`1966`,
    ____wb_netmigration.`1967`,
    ____wb_netmigration.`1968`,
    ____wb_netmigration.`1969`,
    ____wb_netmigration.`1970`,
    ____wb_netmigration.`1971`,
    ____wb_netmigration.`1972`,
    ____wb_netmigration.`1973`,
    ____wb_netmigration.`1974`,
    ____wb_netmigration.`1975`,
    ____wb_netmigration.`1976`,
    ____wb_netmigration.`1977`,
    ____wb_netmigration.`1978`,
    ____wb_netmigration.`1979`,
    ____wb_netmigration.`1980`,
    ____wb_netmigration.`1981`,
    ____wb_netmigration.`1982`,
    ____wb_netmigration.`1983`,
    ____wb_netmigration.`1984`,
    ____wb_netmigration.`1985`,
    ____wb_netmigration.`1986`,
    ____wb_netmigration.`1987`,
    ____wb_netmigration.`1988`,
    ____wb_netmigration.`1989`,
    ____wb_netmigration.`1990`,
    ____wb_netmigration.`1991`,
    ____wb_netmigration.`1992`,
    ____wb_netmigration.`1993`,
    ____wb_netmigration.`1994`,
    ____wb_netmigration.`1995`,
    ____wb_netmigration.`1996`,
    ____wb_netmigration.`1997`,
    ____wb_netmigration.`1998`,
    ____wb_netmigration.`1999`,
    ____wb_netmigration.`2000`,
    ____wb_netmigration.`2001`,
    ____wb_netmigration.`2002`,
    ____wb_netmigration.`2003`,
    ____wb_netmigration.`2004`,
    ____wb_netmigration.`2005`,
    ____wb_netmigration.`2006`,
    ____wb_netmigration.`2007`,
    ____wb_netmigration.`2008`,
    ____wb_netmigration.`2009`,
    ____wb_netmigration.`2010`,
    ____wb_netmigration.`2011`,
    ____wb_netmigration.`2012`,
    ____wb_netmigration.`2013`,
    ____wb_netmigration.`2014`,
    ____wb_netmigration.`2015`,
    ____wb_netmigration.`2016`,
    ____wb_netmigration.`2017`,
    ____wb_netmigration.`2018`,
    ____wb_netmigration.`2019`,
    ____wb_netmigration.`2020`,
    ____wb_netmigration.`2021`,
    ____wb_netmigration.`2022`,
    ____wb_netmigration.`2023` 
FROM
  ____wb_netmigration
  JOIN wb_countries ON ____wb_netmigration.country_code = wb_countries.country_code
  JOIN wb_indicators ON ____wb_netmigration.indicator_code = wb_indicators.indicator_code;
  
#INSERT INTO wb_values (
  country_id,
  indicator_id,
  `1960`, `1961`, `1962`, `1963`, `1964`, `1965`, `1966`, `1967`, `1968`, `1969`,
  `1970`, `1971`, `1972`, `1973`, `1974`, `1975`, `1976`, `1977`, `1978`, `1979`,
  `1980`, `1981`, `1982`, `1983`, `1984`, `1985`, `1986`, `1987`, `1988`, `1989`,
  `1990`, `1991`, `1992`, `1993`, `1994`, `1995`, `1996`, `1997`, `1998`, `1999`,
  `2000`, `2001`, `2002`, `2003`, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`,
  `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`,
  `2020`, `2021`, `2022`, `2023` 
) SELECT
    wb_countries.id,
    wb_indicators.id,
    ____wb_poverty.`1960`,
    ____wb_poverty.`1961`,
    ____wb_poverty.`1962`,
    ____wb_poverty.`1963`,
    ____wb_poverty.`1964`,
    ____wb_poverty.`1965`,
    ____wb_poverty.`1966`,
    ____wb_poverty.`1967`,
    ____wb_poverty.`1968`,
    ____wb_poverty.`1969`,
    ____wb_poverty.`1970`,
    ____wb_poverty.`1971`,
    ____wb_poverty.`1972`,
    ____wb_poverty.`1973`,
    ____wb_poverty.`1974`,
    ____wb_poverty.`1975`,
    ____wb_poverty.`1976`,
    ____wb_poverty.`1977`,
    ____wb_poverty.`1978`,
    ____wb_poverty.`1979`,
    ____wb_poverty.`1980`,
    ____wb_poverty.`1981`,
    ____wb_poverty.`1982`,
    ____wb_poverty.`1983`,
    ____wb_poverty.`1984`,
    ____wb_poverty.`1985`,
    ____wb_poverty.`1986`,
    ____wb_poverty.`1987`,
    ____wb_poverty.`1988`,
    ____wb_poverty.`1989`,
    ____wb_poverty.`1990`,
    ____wb_poverty.`1991`,
    ____wb_poverty.`1992`,
    ____wb_poverty.`1993`,
    ____wb_poverty.`1994`,
    ____wb_poverty.`1995`,
    ____wb_poverty.`1996`,
    ____wb_poverty.`1997`,
    ____wb_poverty.`1998`,
    ____wb_poverty.`1999`,
    ____wb_poverty.`2000`,
    ____wb_poverty.`2001`,
    ____wb_poverty.`2002`,
    ____wb_poverty.`2003`,
    ____wb_poverty.`2004`,
    ____wb_poverty.`2005`,
    ____wb_poverty.`2006`,
    ____wb_poverty.`2007`,
    ____wb_poverty.`2008`,
    ____wb_poverty.`2009`,
    ____wb_poverty.`2010`,
    ____wb_poverty.`2011`,
    ____wb_poverty.`2012`,
    ____wb_poverty.`2013`,
    ____wb_poverty.`2014`,
    ____wb_poverty.`2015`,
    ____wb_poverty.`2016`,
    ____wb_poverty.`2017`,
    ____wb_poverty.`2018`,
    ____wb_poverty.`2019`,
    ____wb_poverty.`2020`,
    ____wb_poverty.`2021`,
    ____wb_poverty.`2022`,
    ____wb_poverty.`2023` 
FROM
  ____wb_poverty
  JOIN wb_countries ON ____wb_poverty.country_code = wb_countries.country_code
  JOIN wb_indicators ON ____wb_poverty.indicator_code = wb_indicators.indicator_code;
  
#INSERT INTO wb_values (
  country_id,
  indicator_id,
  `1960`, `1961`, `1962`, `1963`, `1964`, `1965`, `1966`, `1967`, `1968`, `1969`,
  `1970`, `1971`, `1972`, `1973`, `1974`, `1975`, `1976`, `1977`, `1978`, `1979`,
  `1980`, `1981`, `1982`, `1983`, `1984`, `1985`, `1986`, `1987`, `1988`, `1989`,
  `1990`, `1991`, `1992`, `1993`, `1994`, `1995`, `1996`, `1997`, `1998`, `1999`,
  `2000`, `2001`, `2002`, `2003`, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`,
  `2010`, `2011`, `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`, `2019`,
  `2020`, `2021`, `2022`, `2023` 
) SELECT
    wb_countries.id,
    wb_indicators.id,
    ____wb_unemployment.`1960`,
    ____wb_unemployment.`1961`,
    ____wb_unemployment.`1962`,
    ____wb_unemployment.`1963`,
    ____wb_unemployment.`1964`,
    ____wb_unemployment.`1965`,
    ____wb_unemployment.`1966`,
    ____wb_unemployment.`1967`,
    ____wb_unemployment.`1968`,
    ____wb_unemployment.`1969`,
    ____wb_unemployment.`1970`,
    ____wb_unemployment.`1971`,
    ____wb_unemployment.`1972`,
    ____wb_unemployment.`1973`,
    ____wb_unemployment.`1974`,
    ____wb_unemployment.`1975`,
    ____wb_unemployment.`1976`,
    ____wb_unemployment.`1977`,
    ____wb_unemployment.`1978`,
    ____wb_unemployment.`1979`,
    ____wb_unemployment.`1980`,
    ____wb_unemployment.`1981`,
    ____wb_unemployment.`1982`,
    ____wb_unemployment.`1983`,
    ____wb_unemployment.`1984`,
    ____wb_unemployment.`1985`,
    ____wb_unemployment.`1986`,
    ____wb_unemployment.`1987`,
    ____wb_unemployment.`1988`,
    ____wb_unemployment.`1989`,
    ____wb_unemployment.`1990`,
    ____wb_unemployment.`1991`,
    ____wb_unemployment.`1992`,
    ____wb_unemployment.`1993`,
    ____wb_unemployment.`1994`,
    ____wb_unemployment.`1995`,
    ____wb_unemployment.`1996`,
    ____wb_unemployment.`1997`,
    ____wb_unemployment.`1998`,
    ____wb_unemployment.`1999`,
    ____wb_unemployment.`2000`,
    ____wb_unemployment.`2001`,
    ____wb_unemployment.`2002`,
    ____wb_unemployment.`2003`,
    ____wb_unemployment.`2004`,
    ____wb_unemployment.`2005`,
    ____wb_unemployment.`2006`,
    ____wb_unemployment.`2007`,
    ____wb_unemployment.`2008`,
    ____wb_unemployment.`2009`,
    ____wb_unemployment.`2010`,
    ____wb_unemployment.`2011`,
    ____wb_unemployment.`2012`,
    ____wb_unemployment.`2013`,
    ____wb_unemployment.`2014`,
    ____wb_unemployment.`2015`,
    ____wb_unemployment.`2016`,
    ____wb_unemployment.`2017`,
    ____wb_unemployment.`2018`,
    ____wb_unemployment.`2019`,
    ____wb_unemployment.`2020`,
    ____wb_unemployment.`2021`,
    ____wb_unemployment.`2022`,
    ____wb_unemployment.`2023` 
FROM
  ____wb_unemployment
  JOIN wb_countries ON ____wb_unemployment.country_code = wb_countries.country_code
  JOIN wb_indicators ON ____wb_unemployment.indicator_code = wb_indicators.indicator_code;

We can check on the three tables conforming the **wb_indicators_schema** (first 15 records):

In [60]:
!pip install qgrid

Collecting qgrid
  Downloading qgrid-1.3.1.tar.gz (889 kB)
     ---------------------------------------- 0.0/889.2 kB ? eta -:--:--
     ---------------------------------------- 10.2/889.2 kB ? eta -:--:--
      ------------------------------------ 20.5/889.2 kB 217.9 kB/s eta 0:00:04
     -- ---------------------------------- 61.4/889.2 kB 409.6 kB/s eta 0:00:03
     ----- ------------------------------ 143.4/889.2 kB 774.0 kB/s eta 0:00:01
     ------------------ ------------------- 440.3/889.2 kB 2.1 MB/s eta 0:00:01
     --------------------------------- ---- 778.2/889.2 kB 3.1 MB/s eta 0:00:01
     -------------------------------------- 889.2/889.2 kB 3.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: notebook>=4.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from qgrid) (7.0.8)
Requirement already satisfied: pandas>=0.18.0 in c:\users\ruano\anaconda3\lib\site-packages (from qgrid) (2.2.2)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from qgrid) (7.8.1)
Requirement already satisfied: comm>=0.1.3 in c:\users\ruano\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->qgrid) (0.2.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->qgrid) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\ruano\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->qgrid) (5.14.3)
Requirement already satisfied: widgetsnbextension~=3.6.6 in c:\users\ruano\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->qgrid) (3.6.6)
Requirement already satisfied: ipython>=4.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->qgrid) (8.25.0)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->qgrid) (1.0.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\ruano\anaconda3\lib\site-packages (from notebook>=4.0.0->qgrid) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in c:\users\ruano\anaconda3\lib\site-packages (from notebook>=4.0.0->qgrid) (2.25.1)
Requirement already satisfied: jupyterlab<4.1,>=4.0.2 in c:\users\ruano\anaconda3\lib\site-packages (from notebook>=4.0.0->qgrid) (4.0.11)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\ruano\anaconda3\lib\site-packages (from notebook>=4.0.0->qgrid) (0.2.3)
Requirement already satisfied: tornado>=6.2.0 in c:\users\ruano\anaconda3\lib\site-packages (from notebook>=4.0.0->qgrid) (6.4.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ruano\anaconda3\lib\site-packages (from pandas>=0.18.0->qgrid) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ruano\anaconda3\lib\site-packages (from pandas>=0.18.0->qgrid) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ruano\anaconda3\lib\site-packages (from pandas>=0.18.0->qgrid) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ruano\anaconda3\lib\site-packages (from pandas>=0.18.0->qgrid) (2023.3)
Requirement already satisfied: decorator in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (2.15.1)
Requirement already satisfied: stack-data in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.2.0)
Requirement already satisfied: colorama in c:\users\ruano\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.4.6)
Requirement already satisfied: anyio>=3.1.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.1.4)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (7.10.0)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (5.9.2)
Requirement already satisfied: overrides>=5.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (7.4.0)
Requirement already satisfied: packaging>=22.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (23.2)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.0.10)
Requirement already satisfied: pyzmq>=24 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (25.1.2)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab<4.1,>=4.0.2->notebook>=4.0.0->qgrid) (2.0.4)
Requirement already satisfied: ipykernel in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab<4.1,>=4.0.2->notebook>=4.0.0->qgrid) (6.28.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab<4.1,>=4.0.2->notebook>=4.0.0->qgrid) (2.2.0)
Requirement already satisfied: babel>=2.10 in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (4.19.2)
Requirement already satisfied: requests>=2.31 in c:\users\ruano\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (2.32.2)
Requirement already satisfied: six>=1.5 in c:\users\ruano\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.18.0->qgrid) (1.16.0)
Requirement already satisfied: idna>=2.8 in c:\users\ruano\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\ruano\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\ruano\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (21.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\ruano\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ruano\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\ruano\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\ruano\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\ruano\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\ruano\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (0.10.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (305.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\ruano\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (4.1.0)
Requirement already satisfied: defusedxml in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.5.0)
Requirement already satisfied: tinycss2 in c:\users\ruano\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.2.1)
Requirement already satisfied: fastjsonschema in c:\users\ruano\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.16.2)
Requirement already satisfied: wcwidth in c:\users\ruano\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ruano\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ruano\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ruano\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook>=4.0.0->qgrid) (2024.7.4)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\ruano\anaconda3\lib\site-packages (from ipykernel->jupyterlab<4.1,>=4.0.2->notebook>=4.0.0->qgrid) (1.6.7)
Requirement already satisfied: nest-asyncio in c:\users\ruano\anaconda3\lib\site-packages (from ipykernel->jupyterlab<4.1,>=4.0.2->notebook>=4.0.0->qgrid) (1.6.0)
Requirement already satisfied: psutil in c:\users\ruano\anaconda3\lib\site-packages (from ipykernel->jupyterlab<4.1,>=4.0.2->notebook>=4.0.0->qgrid) (5.9.0)
Requirement already satisfied: executing in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.8.3)
Requirement already satisfied: asttokens in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython>=4.0.0->ipywidgets>=7.0.0->qgrid) (0.2.2)
Requirement already satisfied: webencodings in c:\users\ruano\anaconda3\lib\site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (0.5.1)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in c:\users\ruano\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.1)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=1.11 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid)
  Downloading webcolors-24.8.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: cffi>=1.0.1 in c:\users\ruano\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\ruano\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.5)
Requirement already satisfied: pycparser in c:\users\ruano\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (2.21)
Requirement already satisfied: arrow>=0.15.0 in c:\users\ruano\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.0.0->qgrid) (1.2.3)
Downloading webcolors-24.8.0-py3-none-any.whl (15 kB)
Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Building wheels for collected packages: qgrid
  Building wheel for qgrid (setup.py): started
  Building wheel for qgrid (setup.py): finished with status 'done'
  Created wheel for qgrid: filename=qgrid-1.3.1-py2.py3-none-any.whl size=1761261 sha256=5e09de5a5af2721856b6cd5210f8b3aaa89075e3ff59a196a0a3cad2df88baf5
  Stored in directory: c:\users\ruano\appdata\local\pip\cache\wheels\0a\83\df\0bccd6bcfb1923fcca59ca6f7b04f6b8d19300faf1a4edcc02
Successfully built qgrid
Installing collected packages: webcolors, uri-template, fqdn, isoduration, qgrid
Successfully installed fqdn-1.5.1 isoduration-20.11.0 qgrid-1.3.1 uri-template-1.3.0 webcolors-24.8.0

In [72]:
from sqlalchemy import create_engine
import pandas as pd
from IPython.display import display, HTML

# Configure the connection string
engine = create_engine('mysql+pymysql://root:datapoet@localhost/dap1')

# Query and display the wb_countries table
query_countries = '''
SELECT * FROM wb_countries
LIMIT 15;
'''
df_countries = pd.read_sql(query_countries, engine)

# Display the DataFrame as an HTML table
print("wb_countries Table:")
display(HTML(df_countries.to_html()))

# Query and display the wb_values table
query_values = '''
SELECT * FROM wb_values
LIMIT 15;
'''
df_values = pd.read_sql(query_values, engine)

# Display the DataFrame as an HTML table
print("wb_values Table:")
display(HTML(df_values.to_html()))

# Query and display the wb_indicators table
query_indicators = '''
SELECT * FROM wb_indicators
LIMIT 15;
'''
df_indicators = pd.read_sql(query_indicators, engine)

# Display the DataFrame as an HTML table
print("wb_indicators Table:")
display(HTML(df_indicators.to_html()))

wb_countries Table:

wb_values Table:

wb_indicators Table:

#### 2.2.3.2 **United Nations: Population Division**

For the United Nations data, SQL queries were used to verify and ensure data consistency and finally integrate the tables into the final data model. The **un_database_schema** consists of 4 tables:

In [5]:
pip install ipython-sql mysql-connector-python

Requirement already satisfied: ipython-sql in c:\users\ruano\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: mysql-connector-python in c:\users\ruano\anaconda3\lib\site-packages (9.0.0)
Requirement already satisfied: prettytable in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (3.11.0)
Requirement already satisfied: ipython in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (8.25.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (2.0.30)
Requirement already satisfied: sqlparse in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (0.5.1)
Requirement already satisfied: six in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\ruano\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ruano\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ruano\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: decorator in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: colorama in c:\users\ruano\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\ruano\anaconda3\lib\site-packages (from prettytable->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\ruano\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\ruano\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [9]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [11]:
%sql mysql+mysqlconnector://root:datapoet@localhost/dap1

In [16]:
%%sql
SELECT * FROM un_countries;

 * mysql+mysqlconnector://root:***@localhost/dap1
235 rows affected.

[(4, '   Afghanistan', 'AFG', 5501),
 (8, '   Albania', 'ALB', 925),
 (12, '   Algeria', 'DZA', 912),
 (16, '   American Samoa*', 'ASM', 957),
 (20, '   Andorra', 'AND', 925),
 (24, '   Angola', 'AGO', 911),
 (28, '   Antigua and Barbuda', 'ATG', 915),
 (31, '   Azerbaijan*', 'AZE', 922),
 (32, '   Argentina', 'ARG', 931),
 (36, '   Australia*', 'AUS', 927),
 (40, '   Austria', 'AUT', 926),
 (44, '   Bahamas', 'BHS', 915),
 (48, '   Bahrain', 'BHR', 922),
 (50, '   Bangladesh', 'BGD', 5501),
 (51, '   Armenia', 'ARM', 922),
 (52, '   Barbados', 'BRB', 915),
 (56, '   Belgium', 'BEL', 926),
 (60, '   Bermuda*', 'BMU', 999),
 (64, '   Bhutan', 'BTN', 5501),
 (68, '   Bolivia (Plurinational State of)', 'BOL', 931),
 (70, '   Bosnia and Herzegovina', 'BIH', 925),
 (72, '   Botswana', 'BWA', 913),
 (76, '   Brazil', 'BRA', 931),
 (84, '   Belize', 'BLZ', 916),
 (90, '   Solomon Islands', 'SLB', 928),
 (92, '   British Virgin Islands*', 'VGB', 915),
 (96, '   Brunei Darussalam', 'BRN', 920),
 (100, '   Bulgaria', 'BGR', 923),
 (104, '   Myanmar', 'MMR', 920),
 (108, '   Burundi', 'BDI', 910),
 (112, '   Belarus', 'BLR', 923),
 (116, '   Cambodia', 'KHM', 920),
 (120, '   Cameroon', 'CMR', 911),
 (124, '   Canada', 'CAN', 999),
 (132, '   Cabo Verde', 'CPV', 914),
 (136, '   Cayman Islands*', 'CYM', 915),
 (140, '   Central African Republic', 'CAF', 911),
 (144, '   Sri Lanka', 'LKA', 5501),
 (148, '   Chad', 'TCD', 911),
 (152, '   Chile', 'CHL', 931),
 (156, '   China*', 'CHN', 906),
 (158, '   China, Taiwan Province of China*', 'TWN', 906),
 (170, '   Colombia', 'COL', 931),
 (174, '   Comoros', 'COM', 910),
 (175, '   Mayotte*', 'MYT', 910),
 (178, '   Congo', 'COG', 911),
 (180, '   Democratic Republic of the Congo', 'COD', 911),
 (184, '   Cook Islands*', 'COK', 957),
 (188, '   Costa Rica', 'CRI', 916),
 (191, '   Croatia', 'HRV', 925),
 (192, '   Cuba', 'CUB', 915),
 (196, '   Cyprus*', 'CYP', 922),
 (203, '   Czechia', 'CZE', 923),
 (204, '   Benin', 'BEN', 914),
 (208, '   Denmark*', 'DNK', 924),
 (212, '   Dominica', 'DMA', 915),
 (214, '   Dominican Republic', 'DOM', 915),
 (218, '   Ecuador', 'ECU', 931),
 (222, '   El Salvador', 'SLV', 916),
 (226, '   Equatorial Guinea', 'GNQ', 911),
 (231, '   Ethiopia', 'ETH', 910),
 (232, '   Eritrea', 'ERI', 910),
 (233, '   Estonia', 'EST', 924),
 (234, '   Faroe Islands*', 'FRO', 924),
 (238, '   Falkland Islands (Malvinas)*', 'FLK', 931),
 (242, '   Fiji', 'FJI', 928),
 (246, '   Finland*', 'FIN', 924),
 (250, '   France*', 'FRA', 926),
 (254, '   French Guiana*', 'GUF', 931),
 (258, '   French Polynesia*', 'PYF', 957),
 (262, '   Djibouti', 'DJI', 910),
 (266, '   Gabon', 'GAB', 911),
 (268, '   Georgia*', 'GEO', 922),
 (270, '   Gambia', 'GMB', 914),
 (275, '   State of Palestine*', 'PSE', 922),
 (276, '   Germany', 'DEU', 926),
 (288, '   Ghana', 'GHA', 914),
 (292, '   Gibraltar*', 'GIB', 925),
 (296, '   Kiribati', 'KIR', 954),
 (300, '   Greece', 'GRC', 925),
 (304, '   Greenland*', 'GRL', 999),
 (308, '   Grenada', 'GRD', 915),
 (312, '   Guadeloupe*', 'GLP', 915),
 (316, '   Guam*', 'GUM', 954),
 (320, '   Guatemala', 'GTM', 916),
 (324, '   Guinea', 'GIN', 914),
 (328, '   Guyana', 'GUY', 931),
 (332, '   Haiti', 'HTI', 915),
 (336, '   Holy See*', 'VAT', 925),
 (340, '   Honduras', 'HND', 916),
 (344, '   China, Hong Kong SAR*', 'HKG', 906),
 (348, '   Hungary', 'HUN', 923),
 (352, '   Iceland', 'ISL', 924),
 (356, '   India', 'IND', 5501),
 (360, '   Indonesia', 'IDN', 920),
 (364, '   Iran (Islamic Republic of)', 'IRN', 5501),
 (368, '   Iraq', 'IRQ', 922),
 (372, '   Ireland', 'IRL', 924),
 (376, '   Israel', 'ISR', 922),
 (380, '   Italy', 'ITA', 925),
 (384, "   Côte d'Ivoire", 'CIV', 914),
 (388, '   Jamaica', 'JAM', 915),
 (392, '   Japan', 'JPN', 906),
 (398, '   Kazakhstan', 'KAZ', 5500),
 (400, '   Jordan', 'JOR', 922),
 (404, '   Kenya', 'KEN', 910),
 (408, "   Dem. People's Republic of Korea", 'PRK', 906),
 (410, '   Republic of Korea', 'KOR', 906),
 (414, '   Kuwait', 'KWT', 922),
 (417, '   Kyrgyzstan', 'KGZ', 5500),
 (418, "   Lao People's Democratic Republic", 'LAO', 920),
 (422, '   Lebanon', 'LBN', 922),
 (426, '   Lesotho', 'LSO', 913),
 (428, '   Latvia', 'LVA', 924),
 (430, '   Liberia', 'LBR', 914),
 (434, '   Libya', 'LBY', 912),
 (438, '   Liechtenstein', 'LIE', 926),
 (440, '   Lithuania', 'LTU', 924),
 (442, '   Luxembourg', 'LUX', 926),
 (446, '   China, Macao SAR*', 'MAC', 906),
 (450, '   Madagascar', 'MDG', 910),
 (454, '   Malawi', 'MWI', 910),
 (458, '   Malaysia*', 'MYS', 920),
 (462, '   Maldives', 'MDV', 5501),
 (466, '   Mali', 'MLI', 914),
 (470, '   Malta', 'MLT', 925),
 (474, '   Martinique*', 'MTQ', 915),
 (478, '   Mauritania', 'MRT', 914),
 (480, '   Mauritius*', 'MUS', 910),
 (484, '   Mexico', 'MEX', 916),
 (492, '   Monaco', 'MCO', 926),
 (496, '   Mongolia', 'MNG', 906),
 (498, '   Republic of Moldova*', 'MDA', 923),
 (499, '   Montenegro', 'MNE', 925),
 (500, '   Montserrat*', 'MSR', 915),
 (504, '   Morocco', 'MAR', 912),
 (508, '   Mozambique', 'MOZ', 910),
 (512, '   Oman', 'OMN', 922),
 (516, '   Namibia', 'NAM', 913),
 (520, '   Nauru', 'NRU', 954),
 (524, '   Nepal', 'NPL', 5501),
 (528, '   Netherlands*', 'NLD', 926),
 (531, '   Curaçao*', 'CUW', 915),
 (533, '   Aruba*', 'ABW', 915),
 (534, '   Sint Maarten (Dutch part)*', 'SXM', 915),
 (535, '   Bonaire, Sint Eustatius and Saba*', 'BES', 915),
 (540, '   New Caledonia*', 'NCL', 928),
 (548, '   Vanuatu', 'VUT', 928),
 (554, '   New Zealand*', 'NZL', 927),
 (558, '   Nicaragua', 'NIC', 916),
 (562, '   Niger', 'NER', 914),
 (566, '   Nigeria', 'NGA', 914),
 (570, '   Niue*', 'NIU', 957),
 (578, '   Norway*', 'NOR', 924),
 (580, '   Northern Mariana Islands*', 'MNP', 954),
 (583, '   Micronesia (Fed. States of)', 'FSM', 954),
 (584, '   Marshall Islands', 'MHL', 954),
 (585, '   Palau', 'PLW', 954),
 (586, '   Pakistan', 'PAK', 5501),
 (591, '   Panama', 'PAN', 916),
 (598, '   Papua New Guinea', 'PNG', 928),
 (600, '   Paraguay', 'PRY', 931),
 (604, '   Peru', 'PER', 931),
 (608, '   Philippines', 'PHL', 920),
 (616, '   Poland', 'POL', 923),
 (620, '   Portugal', 'PRT', 925),
 (624, '   Guinea-Bissau', 'GNB', 914),
 (626, '   Timor-Leste', 'TLS', 920),
 (630, '   Puerto Rico*', 'PRI', 915),
 (634, '   Qatar', 'QAT', 922),
 (638, '   Réunion*', 'REU', 910),
 (642, '   Romania', 'ROU', 923),
 (643, '   Russian Federation', 'RUS', 923),
 (646, '   Rwanda', 'RWA', 910),
 (652, '   Saint Barthélemy*', 'BLM', 915),
 (654, '   Saint Helena*', 'SHN', 914),
 (659, '   Saint Kitts and Nevis', 'KNA', 915),
 (660, '   Anguilla*', 'AIA', 915),
 (662, '   Saint Lucia', 'LCA', 915),
 (663, '   Saint Martin (French part)*', 'MAF', 915),
 (666, '   Saint Pierre and Miquelon*', 'SPM', 999),
 (670, '   Saint Vincent and the Grenadines', 'VCT', 915),
 (674, '   San Marino', 'SMR', 925),
 (678, '   Sao Tome and Principe', 'STP', 911),
 (682, '   Saudi Arabia', 'SAU', 922),
 (686, '   Senegal', 'SEN', 914),
 (688, '   Serbia*', 'SRB', 925),
 (690, '   Seychelles', 'SYC', 910),
 (694, '   Sierra Leone', 'SLE', 914),
 (702, '   Singapore', 'SGP', 920),
 (703, '   Slovakia', 'SVK', 923),
 (704, '   Viet Nam', 'VNM', 920),
 (705, '   Slovenia', 'SVN', 925),
 (706, '   Somalia', 'SOM', 910),
 (710, '   South Africa', 'ZAF', 913),
 (716, '   Zimbabwe', 'ZWE', 910),
 (724, '   Spain*', 'ESP', 925),
 (728, '   South Sudan', 'SSD', 910),
 (729, '   Sudan', 'SDN', 912),
 (732, '   Western Sahara', 'ESH', 912),
 (740, '   Suriname', 'SUR', 931),
 (748, '   Eswatini', 'SWZ', 913),
 (752, '   Sweden', 'SWE', 924),
 (756, '   Switzerland', 'CHE', 926),
 (760, '   Syrian Arab Republic', 'SYR', 922),
 (762, '   Tajikistan', 'TJK', 5500),
 (764, '   Thailand', 'THA', 920),
 (768, '   Togo', 'TGO', 914),
 (772, '   Tokelau*', 'TKL', 957),
 (776, '   Tonga', 'TON', 957),
 (780, '   Trinidad and Tobago', 'TTO', 915),
 (784, '   United Arab Emirates', 'ARE', 922),
 (788, '   Tunisia', 'TUN', 912),
 (792, '   Turkey', 'TUR', 922),
 (795, '   Turkmenistan', 'TKM', 5500),
 (796, '   Turks and Caicos Islands*', 'TCA', 915),
 (798, '   Tuvalu', 'TUV', 957),
 (800, '   Uganda', 'UGA', 910),
 (804, '   Ukraine*', 'UKR', 923),
 (807, '   North Macedonia', 'MKD', 925),
 (818, '   Egypt', 'EGY', 912),
 (826, '   United Kingdom*', 'GBR', 924),
 (830, '   Channel Islands*', 'CHI', 924),
 (833, '   Isle of Man*', 'IMN', 924),
 (834, '   United Republic of Tanzania*', 'TZA', 910),
 (840, '   United States of America*', 'USA', 999),
 (850, '   United States Virgin Islands*', 'VIR', 915),
 (854, '   Burkina Faso', 'BFA', 914),
 (858, '   Uruguay', 'URY', 931),
 (860, '   Uzbekistan', 'UZB', 5500),
 (862, '   Venezuela (Bolivarian Republic of)', 'VEN', 931),
 (876, '   Wallis and Futuna Islands*', 'WLF', 957),
 (882, '   Samoa', 'WSM', 957),
 (887, '   Yemen', 'YEM', 922),
 (894, '   Zambia', 'ZMB', 910)]

In [18]:
%%sql
SELECT * FROM un_subregion;

 * mysql+mysqlconnector://root:***@localhost/dap1
22 rows affected.

[(906, 'Eastern Asia', 935),
 (910, 'Eastern Africa', 903),
 (911, 'Middle Africa', 903),
 (912, 'Northern Africa', 903),
 (913, 'Southern Africa', 903),
 (914, 'Western Africa', 903),
 (915, 'Caribbean', 904),
 (916, 'Central America', 904),
 (920, 'South-Eastern Asia', 935),
 (922, 'Western Asia', 935),
 (923, 'Eastern Europe', 908),
 (924, 'Northern Europe', 908),
 (925, 'Southern Europe', 908),
 (926, 'Western Europe', 908),
 (927, 'Australia and New Zealand', 909),
 (928, 'Melanesia', 909),
 (931, 'South America', 904),
 (954, 'Micronesia', 909),
 (957, 'Polynesia', 909),
 (999, 'Northern America', 905),
 (5500, 'Central Asia', 935),
 (5501, 'Southern Asia', 935)]

In [20]:
%%sql
SELECT * FROM un_region;

 * mysql+mysqlconnector://root:***@localhost/dap1
6 rows affected.

[(903, 'Africa'),
 (904, 'Latin America and the Caribbean'),
 (905, 'Northern America'),
 (908, 'Europe'),
 (909, 'Oceania'),
 (935, 'Asia')]

In [24]:
%%sql
SELECT * FROM un_migration_stock
LIMIT 200;

 * mysql+mysqlconnector://root:***@localhost/dap1
200 rows affected.

[(1, 4, 31, 254, 223, 224, 213, 195, 186, 176, 175, 158, 157, 148, 138, 132, 126, 79, 65, 67, 65, 57, 54, 50),
 (2, 4, 32, 20, 20, 20, 16, 9, 9, 9, 1, 2, 3, 3, 2, 2, 2, 19, 18, 17, 13, 7, 7, 7),
 (3, 4, 36, 2729, 7893, 12580, 18617, 30840, 49550, 60879, 1455, 4518, 7330, 10596, 16873, 28587, 37292, 1274, 3375, 5250, 8021, 13967, 20963, 23587),
 (4, 4, 40, 4748, 5357, 5966, 6614, 10055, 41725, 47602, 3194, 3632, 4070, 4461, 6717, 28486, 32347, 1554, 1725, 1896, 2153, 3338, 13239, 15255),
 (5, 4, 48, 215, 236, 258, 392, 613, 664, 860, 154, 167, 178, 267, 414, 457, 601, 61, 69, 80, 125, 199, 207, 259),
 (6, 4, 56, 93, 79, 60, 2479, 4242, 12819, 24670, 46, 40, 31, 1522, 2566, 8950, 17449, 47, 39, 29, 957, 1676, 3869, 7221),
 (7, 4, 68, 2, 1, 0, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0),
 (8, 4, 76, 0, 0, 0, 28, 58, 68, 73, 0, 0, 0, 18, 37, 44, 48, 0, 0, 0, 10, 21, 24, 25),
 (9, 4, 100, 222, 223, 223, 2320, 2450, 3438, 426, 145, 153, 161, 1767, 1945, 2563, 298, 77, 70, 62, 553, 505, 875, 128),
 (10, 4, 112, 140, 216, 292, 281, 270, 282, 277, 106, 152, 199, 192, 185, 192, 190, 34, 64, 93, 89, 85, 90, 87),
 (11, 4, 124, 5321, 13677, 22359, 30718, 40945, 51641, 55954, 2590, 6608, 10786, 15252, 20687, 25859, 28019, 2731, 7069, 11573, 15466, 20258, 25782, 27935),
 (12, 4, 144, 0, 15, 31, 63, 129, 131, 132, 0, 13, 22, 33, 68, 69, 71, 0, 2, 9, 30, 61, 62, 61),
 (13, 4, 188, 25, 11, 3, 3, 5, 4, 4, 11, 5, 1, 1, 1, 1, 1, 14, 6, 2, 2, 4, 3, 3),
 (14, 4, 196, 2, 3, 4, 6, 8, 7, 6, 2, 3, 4, 4, 6, 6, 6, 0, 0, 0, 2, 2, 1, 0),
 (15, 4, 203, 51, 77, 103, 221, 317, 418, 484, 37, 57, 77, 142, 196, 268, 333, 14, 20, 26, 79, 121, 150, 151),
 (16, 4, 208, 354, 1648, 2941, 6609, 9817, 12293, 13715, 212, 903, 1594, 3562, 5286, 6817, 7596, 142, 745, 1347, 3047, 4531, 5476, 6119),
 (17, 4, 218, 18, 21, 23, 28, 44, 112, 167, 11, 13, 14, 17, 27, 59, 96, 7, 8, 9, 11, 17, 53, 71),
 (18, 4, 233, 0, 0, 0, 0, 13, 26, 65, 0, 0, 0, 0, 10, 20, 46, 0, 0, 0, 0, 3, 6, 19),
 (19, 4, 246, 4, 144, 284, 1604, 2342, 4623, 7019, 4, 72, 141, 891, 1281, 2521, 4317, 0, 72, 143, 713, 1061, 2102, 2702),
 (20, 4, 250, 3346, 3455, 3563, 3409, 4470, 6510, 35348, 1909, 1946, 1983, 1946, 2445, 3175, 17287, 1437, 1509, 1580, 1463, 2025, 3335, 18061),
 (21, 4, 268, 0, 0, 42, 39, 39, 40, 40, 0, 0, 22, 21, 21, 22, 23, 0, 0, 20, 18, 18, 18, 17),
 (22, 4, 276, 33279, 51537, 69794, 75824, 80248, 82361, 250444, 21242, 29287, 37331, 41742, 45003, 45975, 153819, 12037, 22250, 32463, 34082, 35245, 36386, 96625),
 (23, 4, 300, 621, 472, 331, 3401, 6704, 5810, 45293, 502, 388, 279, 2741, 5387, 2835, 22835, 119, 84, 52, 660, 1317, 2975, 22458),
 (24, 4, 324, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 0, 0, 0, 0),
 (25, 4, 348, 274, 403, 532, 2385, 1821, 9411, 1816, 122, 224, 326, 1474, 1135, 6602, 1263, 152, 179, 206, 911, 686, 2809, 553),
 (26, 4, 352, 1, 1, 1, 4, 6, 13, 108, 1, 1, 1, 4, 6, 7, 66, 0, 0, 0, 0, 0, 6, 42),
 (27, 4, 356, 14159, 19916, 12794, 15792, 18085, 16851, 16094, 7259, 10318, 6593, 8211, 8743, 7982, 7973, 6900, 9598, 6201, 7581, 9342, 8869, 8121),
 (28, 4, 364, 3980307, 2660518, 2232283, 2376348, 2572558, 2621236, 2710601, 2209668, 1471768, 1232291, 1305236, 1411729, 1429578, 1471475, 1770639, 1188750, 999992, 1071112, 1160829, 1191658, 1239126),
 (29, 4, 368, 241, 284, 269, 313, 320, 312, 314, 160, 114, 68, 143, 156, 178, 170, 81, 170, 201, 170, 164, 134, 144),
 (30, 4, 372, 29, 79, 173, 173, 145, 148, 168, 24, 64, 140, 142, 117, 119, 137, 5, 15, 33, 31, 28, 29, 31),
 (31, 4, 376, 2724, 2836, 2790, 2610, 2462, 2539, 2464, 1282, 1322, 1305, 1235, 1178, 1208, 1173, 1442, 1514, 1485, 1375, 1284, 1331, 1291),
 (32, 4, 380, 271, 236, 201, 3384, 5549, 14893, 18689, 211, 187, 164, 3164, 5208, 13985, 17187, 60, 49, 37, 220, 341, 908, 1502),
 (33, 4, 400, 74, 75, 76, 38, 119, 49, 61, 43, 44, 46, 26, 81, 30, 37, 31, 31, 30, 12, 38, 19, 24),
 (34, 4, 414, 1334, 1068, 1219, 1317, 1794, 2669, 2896, 808, 681, 823, 868, 1170, 1612, 1750, 526, 387, 396, 449, 624, 1057, 1146),
 (35, 4, 428, 20, 22, 24, 24, 25, 27, 46, 8, 15, 22, 23, 24, 21, 26, 12, 7, 2, 1, 1, 6, 20),
 (36, 4, 434, 677, 452, 236, 260, 285, 319, 340, 556, 351, 155, 187, 206, 230, 248, 121, 101, 81, 73, 79, 89, 92),
 (37, 4, 438, 0, 0, 0, 0, 3, 4, 6, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 0, 1, 3),
 (38, 4, 440, 40, 45, 35, 31, 24, 20, 41, 26, 29, 23, 24, 22, 16, 22, 14, 16, 12, 7, 2, 4, 19),
 (39, 4, 442, 0, 0, 0, 0, 0, 0, 433, 0, 0, 0, 0, 0, 0, 295, 0, 0, 0, 0, 0, 0, 138),
 (40, 4, 458, 32, 36, 50, 271, 506, 545, 2478, 18, 20, 27, 154, 284, 317, 1364, 14, 16, 23, 117, 222, 228, 1114),
 (41, 4, 466, 0, 0, 0, 0, 385, 473, 553, 0, 0, 0, 0, 299, 368, 432, 0, 0, 0, 0, 86, 105, 121),
 (42, 4, 516, 64, 61, 58, 45, 43, 42, 44, 26, 25, 23, 18, 18, 18, 19, 38, 36, 35, 27, 25, 24, 25),
 (43, 4, 528, 9865, 14531, 19683, 32187, 30985, 32735, 36418, 5786, 8388, 11252, 18042, 16721, 17469, 19513, 4079, 6143, 8431, 14145, 14264, 15266, 16905),
 (44, 4, 554, 156, 489, 714, 2051, 2314, 2540, 3827, 103, 282, 347, 996, 1122, 1229, 1852, 53, 207, 367, 1055, 1192, 1311, 1975),
 (45, 4, 558, 27, 22, 37, 54, 57, 61, 62, 16, 13, 21, 29, 31, 34, 35, 11, 9, 16, 25, 26, 27, 27),
 (46, 4, 578, 253, 351, 638, 5023, 8836, 13124, 17242, 186, 206, 351, 3053, 5399, 7990, 10934, 67, 145, 287, 1970, 3437, 5134, 6308),
 (47, 4, 586, 3374973, 1291867, 2069977, 1166210, 1990641, 1710378, 1598223, 1723293, 660633, 1106710, 623606, 1017008, 810665, 805362, 1651680, 631234, 963267, 542604, 973633, 899713, 792861),
 (48, 4, 608, 25, 33, 781, 632, 1201, 1220, 1297, 19, 25, 380, 313, 569, 579, 617, 6, 8, 401, 319, 632, 641, 680),
 (49, 4, 616, 219, 187, 160, 151, 147, 139, 184, 194, 166, 142, 135, 132, 126, 168, 25, 21, 18, 16, 15, 13, 16),
 (50, 4, 634, 384, 417, 388, 620, 1356, 1571, 1599, 281, 312, 296, 462, 1087, 1280, 1283, 103, 105, 92, 158, 269, 291, 316),
 (51, 4, 642, 0, 0, 0, 0, 0, 0, 44, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 0, 0, 0, 16),
 (52, 4, 643, 19103, 15576, 11486, 8328, 4999, 5095, 5090, 9374, 9811, 9896, 6935, 3832, 3899, 3896, 9729, 5765, 1590, 1393, 1167, 1196, 1194),
 (53, 4, 682, 166255, 170388, 175068, 216261, 280395, 385241, 481215, 110590, 113637, 117007, 148673, 197352, 266864, 330299, 55665, 56751, 58061, 67588, 83043, 118377, 150916),
 (54, 4, 703, 26, 125, 315, 488, 139, 155, 194, 24, 106, 276, 451, 119, 132, 166, 2, 19, 39, 37, 20, 23, 28),
 (55, 4, 705, 1, 2, 0, 0, 5, 25, 36, 1, 2, 0, 0, 5, 25, 36, 0, 0, 0, 0, 0, 0, 0),
 (56, 4, 710, 59, 36, 30, 52, 75, 96, 111, 37, 24, 20, 30, 42, 54, 69, 22, 12, 10, 22, 33, 42, 42),
 (57, 4, 724, 24, 37, 455, 219, 439, 458, 615, 17, 26, 326, 156, 344, 348, 465, 7, 11, 129, 63, 95, 110, 150),
 (58, 4, 752, 3368, 3997, 4287, 8255, 12697, 53678, 53306, 1889, 2229, 2378, 4435, 7229, 32202, 34479, 1479, 1768, 1909, 3820, 5468, 21476, 18827),
 (59, 4, 756, 1756, 2243, 2740, 3300, 3617, 11929, 15036, 1064, 1411, 1766, 2090, 2188, 7658, 10616, 692, 832, 974, 1210, 1429, 4271, 4420),
 (60, 4, 760, 0, 92, 172, 629, 2605, 1487, 1143, 0, 47, 87, 321, 1328, 779, 585, 0, 45, 85, 308, 1277, 708, 558),
 (61, 4, 762, 8485, 12248, 17118, 12636, 12606, 12393, 12433, 3726, 5517, 7845, 5687, 5703, 5550, 5566, 4759, 6731, 9273, 6949, 6903, 6843, 6867),
 (62, 4, 764, 0, 9, 20, 11, 1, 1, 1, 0, 5, 10, 7, 1, 1, 1, 0, 4, 10, 4, 0, 0, 0),
 (63, 4, 784, 1630, 2088, 2668, 3208, 6878, 7515, 8191, 1161, 1496, 1911, 2219, 4818, 5176, 5640, 469, 592, 757, 989, 2060, 2339, 2551),
 (64, 4, 792, 7652, 9633, 9020, 9360, 11074, 94002, 117595, 3875, 5233, 5149, 5255, 6156, 51608, 60583, 3777, 4400, 3871, 4105, 4918, 42394, 57012),
 (65, 4, 795, 321, 3210, 1784, 808, 345, 231, 198, 158, 1384, 769, 349, 156, 116, 99, 163, 1826, 1015, 459, 189, 115, 99),
 (66, 4, 804, 2552, 2468, 2416, 2207, 2605, 4812, 4891, 1945, 1897, 1874, 1713, 2022, 3736, 3799, 607, 571, 542, 494, 583, 1076, 1092),
 (67, 4, 818, 237, 188, 154, 183, 198, 135, 210, 194, 150, 117, 142, 152, 108, 164, 43, 38, 37, 41, 46, 27, 46),
 (68, 4, 826, 2076, 8160, 14382, 36020, 38029, 45516, 51376, 1533, 5437, 9425, 22321, 23862, 28054, 31482, 543, 2723, 4957, 13699, 14167, 17462, 19894),
 (69, 4, 840, 28444, 37312, 46342, 51965, 59330, 74106, 142504, 15757, 20837, 26035, 29321, 30501, 37912, 72138, 12687, 16475, 20307, 22644, 28829, 36194, 70366),
 (70, 8, 32, 148, 144, 140, 104, 66, 66, 66, 86, 84, 83, 61, 39, 39, 39, 62, 60, 57, 43, 27, 27, 27),
 (71, 8, 36, 984, 1315, 1530, 2270, 2880, 3460, 3941, 681, 803, 873, 1214, 1476, 1793, 2052, 303, 512, 657, 1056, 1404, 1667, 1889),
 (72, 8, 40, 1733, 1955, 2177, 2414, 2681, 3230, 4398, 863, 989, 1116, 1209, 1314, 1568, 2134, 870, 966, 1061, 1205, 1367, 1662, 2264),
 (73, 8, 56, 2157, 2143, 2067, 3277, 6129, 9380, 11937, 1102, 1092, 1056, 1693, 3110, 4711, 5925, 1055, 1051, 1011, 1584, 3019, 4669, 6012),
 (74, 8, 68, 6, 3, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 6, 3, 0, 1, 1, 2, 1),
 (75, 8, 100, 103, 316, 528, 785, 1028, 990, 1351, 54, 165, 276, 408, 538, 520, 777, 49, 151, 252, 377, 490, 470, 574),
 (76, 8, 124, 398, 3263, 6205, 9642, 13610, 15270, 16544, 193, 1574, 2993, 4835, 6956, 7540, 8170, 205, 1689, 3212, 4807, 6654, 7730, 8374),
 (77, 8, 188, 2, 2, 3, 3, 5, 4, 4, 1, 2, 3, 3, 5, 4, 4, 1, 0, 0, 0, 0, 0, 0),
 (78, 8, 191, 0, 83, 157, 165, 172, 173, 160, 0, 41, 78, 77, 76, 76, 70, 0, 42, 79, 88, 96, 97, 90),
 (79, 8, 192, 242, 184, 226, 40, 6, 1, 0, 133, 98, 113, 22, 4, 1, 0, 109, 86, 113, 18, 2, 0, 0),
 (80, 8, 196, 69, 98, 126, 190, 291, 266, 274, 41, 57, 72, 107, 166, 153, 159, 28, 41, 54, 83, 125, 113, 115),
 (81, 8, 203, 44, 66, 88, 184, 262, 309, 487, 28, 42, 56, 123, 180, 209, 299, 16, 24, 32, 61, 82, 100, 188),
 (82, 8, 208, 5, 45, 84, 173, 249, 347, 568, 3, 19, 35, 77, 113, 162, 274, 2, 26, 49, 96, 136, 185, 294),
 (83, 8, 218, 8, 19, 30, 36, 57, 71, 73, 4, 10, 16, 19, 30, 38, 43, 4, 9, 14, 17, 27, 33, 30),
 (84, 8, 233, 0, 0, 0, 0, 7, 20, 41, 0, 0, 0, 0, 7, 15, 25, 0, 0, 0, 0, 0, 5, 16),
 (85, 8, 246, 0, 17, 34, 114, 174, 336, 706, 0, 11, 22, 94, 148, 250, 485, 0, 6, 12, 20, 26, 86, 221),
 (86, 8, 250, 3391, 3501, 3611, 5747, 6286, 6967, 8925, 1857, 1890, 1924, 3015, 3284, 3550, 4560, 1534, 1611, 1687, 2732, 3002, 3417, 4365),
 (87, 8, 268, 0, 0, 11, 10, 10, 10, 9, 0, 0, 4, 4, 4, 4, 4, 0, 0, 7, 6, 6, 6, 5),
 (88, 8, 276, 5211, 8303, 11394, 13162, 14532, 32767, 61063, 4451, 5370, 6288, 7015, 7573, 17040, 32785, 760, 2933, 5106, 6147, 6959, 15727, 28278),
 (89, 8, 300, 63963, 230218, 400253, 423598, 463157, 436566, 446614, 42970, 138742, 235135, 236038, 245048, 222722, 242083, 20993, 91476, 165118, 187560, 218109, 213844, 204531),
 (90, 8, 324, 0, 0, 0, 0, 0, 11, 9, 0, 0, 0, 0, 0, 7, 7, 0, 0, 0, 0, 0, 4, 2),
 (91, 8, 348, 96, 113, 129, 159, 189, 228, 503, 34, 49, 63, 79, 95, 129, 358, 62, 64, 66, 80, 94, 99, 145),
 (92, 8, 352, 10, 15, 20, 30, 39, 45, 220, 3, 5, 7, 13, 18, 25, 145, 7, 10, 13, 17, 21, 20, 75),
 (93, 8, 372, 57, 158, 346, 347, 291, 297, 340, 34, 91, 204, 213, 171, 173, 200, 23, 67, 142, 134, 120, 124, 140),
 (94, 8, 380, 44935, 159672, 274408, 360959, 440648, 444887, 486187, 31662, 88919, 146176, 190016, 231439, 227638, 244913, 13273, 70753, 128232, 170943, 209209, 217249, 241274),
 (95, 8, 428, 4, 6, 8, 7, 7, 9, 12, 2, 3, 4, 4, 5, 5, 6, 2, 3, 4, 3, 2, 4, 6),
 (96, 8, 434, 315, 266, 223, 245, 268, 300, 320, 209, 171, 139, 169, 185, 207, 224, 106, 95, 84, 76, 83, 93, 96),
 (97, 8, 438, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2),
 (98, 8, 440, 0, 0, 0, 0, 0, 4, 28, 0, 0, 0, 0, 0, 3, 14, 0, 0, 0, 0, 0, 1, 14),
 (99, 8, 442, 290, 275, 264, 229, 197, 300, 1058, 151, 143, 136, 125, 115, 177, 517, 139, 132, 128, 104, 82, 123, 541),
 (100, 8, 466, 0, 0, 0, 0, 1028, 1264, 1482, 0, 0, 0, 0, 461, 566, 666, 0, 0, 0, 0, 567, 698, 816),
 (101, 8, 470, 16, 19, 48, 76, 63, 106, 229, 6, 7, 19, 28, 29, 52, 122, 10, 12, 29, 48, 34, 54, 107),
 (102, 8, 499, 0, 0, 0, 0, 2015, 2754, 2763, 0, 0, 0, 0, 829, 1143, 1154, 0, 0, 0, 0, 1186, 1611, 1609),
 (103, 8, 528, 181, 267, 362, 662, 894, 1324, 2402, 107, 155, 206, 343, 485, 666, 1226, 74, 112, 156, 319, 409, 658, 1176),
 (104, 8, 578, 21, 81, 149, 274, 435, 969, 2174, 13, 42, 81, 156, 226, 564, 1239, 8, 39, 68, 118, 209, 405, 935),
 (105, 8, 608, 421, 566, 582, 471, 114, 116, 122, 209, 276, 286, 236, 55, 56, 60, 212, 290, 296, 235, 59, 60, 62),
 (106, 8, 616, 82, 70, 60, 94, 131, 124, 165, 51, 43, 36, 73, 111, 107, 144, 31, 27, 24, 21, 20, 17, 21),
 (107, 8, 620, 11, 24, 40, 45, 44, 50, 55, 7, 15, 25, 26, 24, 25, 28, 4, 9, 15, 19, 20, 25, 27),
 (108, 8, 642, 591, 632, 675, 690, 790, 3, 823, 264, 290, 315, 329, 379, 2, 612, 327, 342, 360, 361, 411, 1, 211),
 (109, 8, 643, 1026, 988, 915, 578, 230, 234, 232, 503, 527, 532, 337, 136, 137, 137, 523, 461, 383, 241, 94, 97, 95),
 (110, 8, 674, 27, 28, 31, 30, 30, 37, 39, 6, 5, 5, 7, 7, 8, 7, 21, 23, 26, 23, 23, 29, 32),
 (111, 8, 688, 57, 364, 495, 489, 478, 467, 475, 13, 77, 96, 91, 88, 85, 88, 44, 287, 399, 398, 390, 382, 387),
 (112, 8, 703, 6, 29, 60, 68, 76, 99, 133, 4, 25, 51, 58, 65, 84, 114, 2, 4, 9, 10, 11, 15, 19),
 (113, 8, 705, 15, 51, 76, 49, 96, 148, 146, 10, 34, 45, 19, 48, 79, 47, 5, 17, 31, 30, 48, 69, 99),
 (114, 8, 710, 78, 63, 69, 90, 131, 168, 195, 34, 28, 31, 38, 53, 67, 92, 44, 35, 38, 52, 78, 101, 103),
 (115, 8, 724, 162, 359, 712, 1094, 1807, 1938, 2615, 83, 190, 383, 616, 1044, 1050, 1395, 79, 169, 329, 478, 763, 888, 1220),
 (116, 8, 752, 293, 348, 374, 684, 1134, 2023, 5724, 160, 189, 202, 379, 642, 1145, 3276, 133, 159, 172, 305, 492, 878, 2448),
 (117, 8, 756, 1333, 1316, 1304, 1492, 1721, 2416, 4323, 803, 723, 646, 708, 754, 1125, 2050, 530, 593, 658, 784, 967, 1291, 2273),
 (118, 8, 792, 801, 1939, 3086, 3192, 3292, 3261, 4554, 426, 993, 1563, 1583, 1595, 1540, 1972, 375, 946, 1523, 1609, 1697, 1721, 2582),
 (119, 8, 807, 45001, 58009, 69367, 69782, 70230, 67799, 68113, 18759, 24182, 28917, 29077, 28250, 27915, 28040, 26242, 33827, 40450, 40705, 41980, 39884, 40073),
 (120, 8, 818, 111, 96, 88, 105, 113, 77, 119, 74, 61, 53, 66, 69, 51, 75, 37, 35, 35, 39, 44, 26, 44),
 (121, 8, 826, 156, 1181, 2227, 7335, 7743, 9267, 10458, 91, 748, 1417, 4644, 4961, 5838, 6553, 65, 433, 810, 2691, 2782, 3429, 3905),
 (122, 8, 840, 5627, 22440, 39644, 54825, 72085, 91865, 97252, 3220, 12978, 22984, 31914, 38493, 45147, 47248, 2407, 9462, 16660, 22911, 33592, 46718, 50004),
 (123, 8, 862, 17, 16, 16, 16, 18, 19, 17, 9, 8, 8, 8, 9, 9, 9, 8, 8, 8, 8, 9, 10, 8),
 (124, 12, 32, 229, 224, 219, 163, 104, 104, 103, 136, 134, 133, 99, 64, 64, 64, 93, 90, 86, 64, 40, 40, 39),
 (125, 12, 36, 665, 950, 1170, 1330, 1380, 1600, 1776, 397, 595, 750, 811, 847, 982, 1051, 268, 355, 420, 519, 533, 618, 725),
 (126, 12, 40, 711, 802, 893, 990, 1100, 1340, 1581, 541, 613, 686, 755, 833, 1031, 1158, 170, 189, 207, 235, 267, 309, 423),
 (127, 12, 56, 26077, 24149, 21519, 18450, 22372, 25666, 27491, 15089, 13661, 11875, 10605, 12539, 14539, 15180, 10988, 10488, 9644, 7845, 9833, 11127, 12311),
 (128, 12, 68, 4, 7, 10, 7, 3, 4, 3, 3, 5, 7, 5, 2, 2, 2, 1, 2, 3, 2, 1, 2, 1),
 (129, 12, 76, 0, 0, 0, 91, 183, 215, 232, 0, 0, 0, 46, 92, 108, 120, 0, 0, 0, 45, 91, 107, 112),
 (130, 12, 100, 32, 105, 178, 266, 350, 347, 460, 23, 60, 98, 142, 187, 194, 283, 9, 45, 80, 124, 163, 153, 177),
 (131, 12, 112, 27, 41, 55, 53, 50, 53, 51, 24, 35, 46, 44, 41, 44, 44, 3, 6, 9, 9, 9, 9, 7),
 (132, 12, 124, 3743, 12014, 20571, 34754, 51080, 64223, 69587, 1823, 5803, 9923, 18102, 27443, 33698, 36513, 1920, 6211, 10648, 16652, 23637, 30525, 33074),
 (133, 12, 188, 44, 21, 9, 7, 13, 12, 14, 19, 9, 4, 3, 5, 5, 6, 25, 12, 5, 4, 8, 7, 8),
 (134, 12, 191, 0, 0, 0, 28, 56, 56, 50, 0, 0, 0, 13, 27, 27, 24, 0, 0, 0, 15, 29, 29, 26),
 (135, 12, 192, 103, 78, 54, 35, 22, 13, 8, 55, 40, 26, 16, 9, 5, 3, 48, 38, 28, 19, 13, 8, 5),
 (136, 12, 196, 9, 13, 16, 25, 38, 34, 34, 5, 7, 8, 13, 20, 18, 18, 4, 6, 8, 12, 18, 16, 16),
 (137, 12, 203, 80, 121, 161, 408, 616, 686, 805, 69, 105, 140, 366, 559, 583, 675, 11, 16, 21, 42, 57, 103, 130),
 (138, 12, 208, 526, 717, 907, 920, 892, 913, 1004, 395, 506, 617, 601, 560, 551, 594, 131, 211, 290, 319, 332, 362, 410),
 (139, 12, 218, 16, 18, 20, 25, 38, 48, 50, 12, 13, 15, 18, 28, 37, 40, 4, 5, 5, 7, 10, 11, 10),
 (140, 12, 233, 0, 0, 0, 0, 14, 24, 32, 0, 0, 0, 0, 11, 20, 26, 0, 0, 0, 0, 3, 4, 6),
 (141, 12, 246, 233, 305, 377, 539, 635, 781, 1014, 216, 271, 327, 441, 510, 615, 774, 17, 34, 50, 98, 125, 166, 240),
 (142, 12, 250, 788914, 814417, 839920, 1337210, 1343555, 1489151, 1637211, 446449, 454931, 463414, 676380, 727715, 787832, 867851, 342465, 359486, 376506, 660830, 615840, 701319, 769360),
 (143, 12, 254, 95, 94, 93, 88, 83, 359, 403, 50, 48, 46, 42, 39, 209, 235, 45, 46, 47, 46, 44, 150, 168),
 (144, 12, 258, 605, 664, 710, 743, 717, 681, 681, 386, 418, 441, 463, 455, 432, 432, 219, 246, 269, 280, 262, 249, 249),
 (145, 12, 266, 34, 45, 57, 62, 72, 100, 108, 20, 26, 35, 38, 44, 65, 72, 14, 19, 22, 24, 28, 35, 36),
 (146, 12, 268, 0, 0, 18, 17, 17, 17, 16, 0, 0, 7, 7, 7, 7, 7, 0, 0, 11, 10, 10, 10, 9),
 (147, 12, 276, 8493, 12366, 16238, 17681, 18744, 19237, 25819, 6415, 9659, 12903, 13162, 13291, 13607, 18684, 2078, 2707, 3335, 4519, 5453, 5630, 7135),
 (148, 12, 288, 7, 7, 8, 11, 11, 13, 13, 5, 5, 6, 8, 8, 10, 11, 2, 2, 2, 3, 3, 3, 2),
 (149, 12, 300, 203, 258, 317, 722, 1167, 1099, 407, 164, 176, 189, 575, 996, 932, 205, 39, 82, 128, 147, 171, 167, 202),
 (150, 12, 312, 74, 99, 124, 137, 150, 144, 142, 36, 47, 58, 63, 69, 63, 62, 38, 52, 66, 74, 81, 81, 80),
 (151, 12, 324, 0, 0, 0, 0, 0, 7044, 6766, 0, 0, 0, 0, 0, 4305, 4147, 0, 0, 0, 0, 0, 2739, 2619),
 (152, 12, 348, 263, 365, 467, 575, 686, 684, 929, 252, 301, 351, 434, 520, 487, 693, 11, 64, 116, 141, 166, 197, 236),
 (153, 12, 352, 10, 17, 23, 24, 24, 40, 68, 8, 13, 18, 18, 17, 31, 51, 2, 4, 5, 6, 7, 9, 17),
 (154, 12, 372, 113, 313, 686, 688, 576, 588, 673, 81, 221, 490, 504, 410, 416, 477, 32, 92, 196, 184, 166, 172, 196),
 (155, 12, 376, 19544, 25514, 30056, 36950, 44292, 45680, 44358, 9202, 11797, 13880, 17046, 20378, 20896, 20292, 10342, 13717, 16176, 19904, 23914, 24784, 24066),
 (156, 12, 380, 6171, 10991, 15810, 19139, 23713, 21908, 22363, 3826, 7501, 11175, 12733, 15472, 13832, 13976, 2345, 3490, 4635, 6406, 8241, 8076, 8387),
 (157, 12, 400, 222, 320, 417, 313, 646, 267, 345, 63, 116, 169, 178, 342, 108, 139, 159, 204, 248, 135, 304, 159, 206),
 (158, 12, 428, 6, 9, 12, 14, 17, 15, 18, 5, 8, 10, 12, 15, 12, 14, 1, 1, 2, 2, 2, 3, 4),
 (159, 12, 434, 1551, 2079, 2642, 2911, 3195, 3577, 3830, 530, 879, 1271, 1669, 1843, 2049, 2231, 1021, 1200, 1371, 1242, 1352, 1528, 1599),
 (160, 12, 438, 0, 0, 0, 0, 4, 6, 6, 0, 0, 0, 0, 3, 3, 2, 0, 0, 0, 0, 1, 3, 4),
 (161, 12, 440, 0, 0, 0, 0, 0, 8, 11, 0, 0, 0, 0, 0, 5, 8, 0, 0, 0, 0, 0, 3, 3),
 (162, 12, 442, 98, 92, 88, 76, 66, 100, 1113, 58, 49, 41, 38, 36, 55, 607, 40, 43, 47, 38, 30, 45, 506),
 (163, 12, 466, 380, 507, 554, 2270, 385, 473, 553, 245, 272, 263, 1043, 246, 302, 355, 135, 235, 291, 1227, 139, 171, 198),
 (164, 12, 470, 21, 25, 31, 38, 43, 72, 155, 15, 17, 22, 26, 31, 53, 119, 6, 8, 9, 12, 12, 19, 36),
 (165, 12, 474, 45, 68, 91, 95, 99, 114, 113, 22, 32, 41, 42, 42, 46, 46, 23, 36, 50, 53, 57, 68, 67),
 (166, 12, 478, 1450, 1549, 1601, 1617, 1133, 1634, 1788, 808, 927, 1024, 1057, 768, 1085, 1191, 642, 622, 577, 560, 365, 549, 597),
 (167, 12, 484, 47, 87, 131, 109, 99, 102, 110, 24, 53, 84, 73, 71, 74, 81, 23, 34, 47, 36, 28, 28, 29),
 (168, 12, 504, 9188, 8429, 8877, 9412, 10231, 13194, 14497, 4858, 4396, 4559, 4769, 5157, 6622, 7466, 4330, 4033, 4318, 4643, 5074, 6572, 7031),
 (169, 12, 516, 716, 684, 637, 503, 484, 473, 505, 336, 323, 302, 237, 229, 225, 241, 380, 361, 335, 266, 255, 248, 264),
 (170, 12, 528, 1764, 2694, 3717, 4026, 3893, 3855, 4219, 1255, 1898, 2604, 2662, 2498, 2384, 2543, 509, 796, 1113, 1364, 1395, 1471, 1676),
 (171, 12, 540, 513, 594, 676, 719, 763, 586, 621, 291, 333, 376, 401, 427, 299, 317, 222, 261, 300, 318, 336, 287, 304),
 (172, 12, 558, 50, 40, 68, 99, 105, 113, 117, 27, 21, 33, 45, 48, 52, 55, 23, 19, 35, 54, 57, 61, 62),